language: python
python:
- '2.7'
jdk:
- oraclejdk7
addons:
  postgresql: '9.4'
before_script:
- echo $JAVA_OPTS
- export JAVA_OPTS=-Xmx512m
- echo -e 'Host github.com\n\tStrictHostKeyChecking no\n' >> ~/.ssh/config
- pip uninstall --yes psqlgraph || true
- pip install pipenv
- pipenv install --dev
- pipenv run python test/setup_test_psqlgraph.py
script: pipenv run py.test -v test
deploy:
  provider: pypi
  user: uc-ctds
  skip_existing: true
  on:
    branch: 123
  password:
    secure: Y5+KjQ5tcN+rzXDBxDFgt55WwFoE6v+dgUNUkAuZTwp27BftdPzsYH3JwLkPv0Ji8Yj7zDXMVfIEEUWxev8GQlbtQ6avPbx/CwAcHEKZpVGEPGb1I82K5MHGXkPvKowDfjpNz6IYZ1XLkBV+PYMYT0RLxg1p4of5f4zMm3emcBZLvgwvdGl8JIsX5lUqST5k+GxwjYflvKPNHWxCp57nYNmlalLJXSeyls0/sqaFd3qQhq/u5aMPeQwvQwAA8Cq4bu5asQa6Jc2ej8ldfIBhL7QmP/3RN1lzlLHO+IP3h0wScByOxIhqNAZaUbjfY3inB/8lVcc6ffvSrShL8IrCGSoe+OXg1bOAUogMleI8zXoXQQlUfst+HRLECdTYdBiFQ8jmkjfsQe9V4Axd3dNWeYh3ZMvQjY3wHlyG4f+gO97iEDxMTLRwKCjIKDHRdV7TW1mV50FveVW/kYRqhEQ2h2oQUDBevIUTj4/Tfun39PMbBMoZi+YzJlC16VLr8Oee4lU0RO1xGA5sXslPzHJfqNZCWWR9O7ptb3wQscP9+TaTW3SrKZ8HhRjl5aUbGsDT/cgseNq/YvyQKfbi7Zp6MDM3p7OAbQCBMz49NuGI4iEFXzV15wtnWZrJHM7Ghhj2tC4Ax4eJbIS6WWVDyC7LYsNKPgHK2m2D6pjwJgQxMgg=
