language: python
python:
    - "2.7"
# command to run tests
jdk:
  - oraclejdk7

addons:
  postgresql: '9.4'

before_script:
  - "echo $JAVA_OPTS"
  - "export JAVA_OPTS=-Xmx512m"
  - echo -e 'Host github.com\n\tStrictHostKeyChecking no\n' >> ~/.ssh/config
  - pip uninstall --yes psqlgraph || true
  - yes | python setup.py install
  - cd test; python setup_test_psqlgraph.py
script: "cd test; py.test -v"
